### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/actividad-4-mapa-mental-0eeixl-1#2]
[trabajo de mate er.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-0eeixl-1/files/12704029/trabajo.de.mate.er.pdf)

**Comment by elisa1223** [comment]
Manejo conceptual y dominio del tema 20%
Relacion entre los conceptos incluidos en el mapa 20%
Calidad de la presentación 22%
Jerarquía 17%

Calificación 15.8 / 20
Evaluado por el quipo de Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Revisado...
